/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 eyeball.gltf 
Author: memartel (https://sketchfab.com/memartel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-eyeball-free-f3c0a0638e784fa0b018e1ad8856eb7a
Title: blue_eyeball_free
*/

// eslint-disable-next-line no-unused-vars
import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/eyeball.gltf')
  return (
    <group {...props} dispose={null}>
      {/* Rotate the entire model to face upwards */}
      <group rotation={[-Math.PI / -2.3, 0, 0]}>
        <mesh geometry={nodes.Object_7.geometry} material={materials.blinn2} rotation={[Math.PI / 2, 0, 0]} scale={2} />
      </group>
    </group>
  )
}

useGLTF.preload('/eyeball.gltf')
