/** @type {import('tailwindcss').Config} */
export const content = ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"];
export const theme = {
  extend: {
    colors: {
      varDARKBEAKTOP: "#785001",
      varMEDBEAKTOP: "#b67902",
      varLIGHTBEAKTOP: "#fca802",
      varDARKDUCKHEAD: "#1e3b28",
      varMEDDUCKHEAD: "#284f35",
      varLIGHTDUCKHEAD: "#528f85",
      varDARKBLUEFEATHER: "#24558d",
      varMEDBLUEFEATHER: "#2a61a1",
      varLIGHTBLUEFEATHER: "#419aff",
      varDARKDUCKCHEEKS: "#362e47",
      varMEDDUCKCHEEKS: "#6b5b8d",
      varLIGHTDUCKCHEEKS: "#a088d2",
      varDARKNECK: "#412a32",
      varMEDNECK: "#98648d",
      varLIGHTNECK: "#c68199",
      varDARKWING: "#3c302e",
      varMEDWING: "#806661",
      varLIGHTWING: "#cfa69d",
      varDARKBEAK: "#70181a",
      varMEDBEAK: "#962023",
      varLIGHTBEAK: "#d72d32",
      varDARKSPACE: "#08121c",
      varMEDSPACE: "#1b3854",
      varLIGHTSPACE: "#264d73",
      varBoneWhite: "#fff9d7",
      varDCDARKBLUE: "#012344",
      varDCMEDBLUE: "#01366a",
      varDCLIGHTBLUE: "#01366a",
      varDCDARKGREY: "#484a4d",
      varDCMEDGREY: "#6b6e73",
      varDCLIGHTGREY: "#b2b7bf",
      varDCBLUEGREY: "#33485d",
    },
    fontFamily: {
                'Aclonica-Regular': ['Aclonica-Regular', 'sans-serif'],
            'ArchivoBlack-Regular': ['ArchivoBlack-Regular', 'sans-serif'],
            'Blackbeard-ld7V' : ['Blackbeard-ld7V', 'cursive'],
            'BlackOpsOne-Regular': ['BlackOpsOne-Regular', 'cursive'],
            'Borel-Regular': ['Borel-Regular', 'sans-serif'],
            'Caprasimo-Regular': ['Caprasimo-Regular', 'cursive'],
            'Caprasimo': ['Caprasimo', 'cursive'],
            'Changa-Regular': ['Changa-Regular', 'sans-serif'],
            'Changa-VariableFont_wght': ['Changa-VariableFont_wght', 'sans-serif'],
            'ChunkFive-Regular': ['ChunkFive-Regular', 'sans-serif'],
            'Creepster-Regular': ['Creepster-Regular', 'cursive'],
            'DMSerifDisplay-Italic': ['DMSerifDisplay-Italic', 'serif'],
            'DMSerifDisplay-Regular': ['DMSerifDisplay-Regular', 'serif'],
            'DMSerifDisplay': ['DM Serif Display-italic', 'serif'],
            'EmilysCandy-Regular': ['EmilysCandy-Regular', 'cursive'],
            'HoltwoodOneSC-Regular': ['HoltwoodOneSC-Regular', 'sans-serif'],
            'HoltwoodOneSC': ['Holtwood One SC', 'sans-serif'],
            'Iceberg-Regular': ['Iceberg-Regular', 'cursive'],
            'Itim-Regular': ['Itim-Regular, cursive'],
            'Kingthings_Petrock': ['Kingthings_Petrock', 'cursive'],
            'Kranky-Regular': ['Kranky-Regular', 'cursive'],
            'LibreBaskerville-Bold': ['LibreBaskerville-Bold', 'serif'],
            'LibreBaskerville-Italic': ['LibreBaskerville-Italic', 'serif'],
            'LibreBaskerville-Regular': ['LibreBaskerville-Regular', 'serif'],
            'MedievalSharp-Regular': ['MedievalSharp-Regular', 'cursive'],
            'MetalMania-Regular': ['MetalMania-Regular', 'cursive'],
            'Metamorphous-Regular': ['Metamorphous-Regular', 'cursive'],
             'Nosifer-Regular': ['Nosifer-Regular', 'cursive'],
             'NotoSans-Italic-VariableFont_wdth,wght': ['NotoSans-Italic-VariableFont_wdth,wght', 'sans-serif'],
             'NotoSans-VariableFont_wdth,wght': ['NotoSans-VariableFont_wdth,wght', 'sans-serif'],
             'NovaCut-Regular': ['NovaCut-Regular', 'sans-serif'],
             'Orbitron-Regular': ['Orbitron-Regular', 'sans-serif'],
             'Orbitron-VariableFont_wght': ['Orbitron-VariableFont_wght', 'sans-serif'],
             'PermanentMarker-Regular': ['PermanentMarker-Regular', 'cursive'],
             'PTSerif-Bold': ['PTSerif-Bold', 'serif'],
             'PTSerif-BoldItalic': ['PTSerif-BoldItalic', 'serif'],
             'PTSerif-Italic': ['PTSerif-Italic', 'serif'],
             'PTSerif-Regular': ['PTSerif-Regular', 'serif'],
             'Rye-Regular': ['Rye-Regular', 'cursive'],
             'Sansita-Italic': ['Sansita-Italic', 'sans-serif'],
             'Sansita-Regular': ['Sansita-Regular', 'sans-serif'],
              'Sixtyfour-Regular-VariableFont': ['Sixtyfour-Regular-VariableFont', 'cursive'],
              'Sixtyfour-Regular': ['Sixtyfour-Regular', 'cursive'],
              'Yellowtail-Regular': ['Yellowtail-Regular', 'cursive'],
            
            
			},

    screens: {
      xxxs: "250px",
      xxs: "320px",
      xs: "420px",
      sm: "460px",
      md: "685px",
      lg: "1024px",
      xl: "1280px",
    },
  },
};

export const plugins = [];
