/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 eyeball.gltf 
Author: memartel (https://sketchfab.com/memartel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-eyeball-free-f3c0a0638e784fa0b018e1ad8856eb7a
Title: blue_eyeball_free
*/

// eslint-disable-next-line no-unused-vars
import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("./Helmet.gltf");
  return (
    <group {...props} dispose={null}>
    <group rotation={[-Math.PI / 2, 0, 3]} position={[0, -2.5, 0]} scale={.175}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.BadgeFront} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.BadgeLeft} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.BadgeRight} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Bullets} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Card} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.CigaretteBox} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.DogTag} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.FrontStrap} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.HoldingStrap} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.InnerShell} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.OuterShell} />
      <mesh geometry={nodes.Object_13.geometry} material={materials['Straps.Fasten']} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Straps.Unfasten']} />
    </group>
  </group>
  );
}

useGLTF.preload("/Helmet.gltf");
