/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 helmet.gltf 
Author: RomarovArt (https://sketchfab.com/RomarArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/classic-m1-helmet-455cc3674c294fa4a3c86134e18e6181
Title: Classic M1 Helmet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/helmet.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.BadgeFront} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.BadgeLeft} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.BadgeRight} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Bullets} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Card} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.CigaretteBox} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.DogTag} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.FrontStrap} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.HoldingStrap} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.InnerShell} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.OuterShell} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Straps.Fasten']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Straps.Unfasten']} />
      </group>
    </group>
  )
}

useGLTF.preload('/helmet.gltf')
